### ISSUE TITLE
Select framework

### ISSUE THREAD

**Issue by aidnem** [team401/Copper-Console#1]
Currently between choices on framework (between Node.js with Electron and Python with Pygame or similar).

Pros of Python
- [pyntcore library](https://robotpy.readthedocs.io/en/stable/install/pyntcore.html)
- aiden is familiar with python

Pros of Javascript
- Seems a little bit less sketchy
- Electron is more widely used
- Easier to package/install on final computers where the app will be used (maybe?)

Overall leaning towards Python right now. Discuss at standup.

**Comment by aidnem** [comment]
@jkleiber I vote that we go with Electron and NodeJS because the developer experience is passable (I'm using typescript and it seems to be working fine) and it's incredibly easy to package (just run one command, and electron-forge bundles an executable which seems to run just fine). I'll make a commit at some point tonight or tomorrow and then we can merge the javascript version onto the main branch and do away with python unless you have any concerns.

**Comment by jkleiber** [comment]
Sounds good @aidnem , thanks for doing the trade study on this

**Comment by redPlover** [comment]
That sounds great, would it be possible/easy to add CI for building releases automagically later?

**Comment by jkleiber** [comment]
> That sounds great, would it be possible/easy to add CI for building releases automagically later?

I would suggest opening a new issue for this

**Comment by aidnem** [comment]
I've created an issue with links to potential solutions here: #2 
By the looks of it, it shouldn't be too difficult to do.

**Comment by jkleiber** [comment]
@aidnem We should definitely prioritize building the app up with the features we want (we should create tickets for what those features are as well). If needed I can work on the CI configuration issue

**Comment by aidnem** [comment]
@jkleiber Absolutely, I'm working on cleaning up the code at the moment (I pretty much wrote it as fast as I could originally so the code style is atrocious) and then I can commit it sometime today and we can work from there to add more features. I can also add my network tables simulation code somewhere (probably my own GitHub account) for easier testing so that we don't depend on the actual robot to test network tables.
I'm not very experienced working with GitHub CI, so if you could do that it would be great.
I'll be adding more tickets for features soon as well.

**Comment by jkleiber** [comment]
@aidnem Let's put the network tables code in this repo, we can test easily from here even if it's not a finished product yet

**Comment by aidnem** [comment]
@jkleiber All commits are done for the most basic possible electron app (including network tables sim code). I'll make a PR soon if you don't have any objections.

**Comment by jkleiber** [comment]
I never have objections for creating PRs, the more the better
