### ISSUE TITLE
Copper Console Network Table Specification

### ISSUE THREAD

**Issue by aidnem** [team401/Copper-Console#8]
CopperConsole should get its own network table, this issue can be to both define the specification. As new features are proposed, new issues can be created to track their actual implementation into the code, while this issue remains a good place to reference the interface as a whole.

Here's the schema so far:
- `CopperConsole/robotPose` - Pose2D describing the robot's position. An array of doubles in the order: [x, y, rotation].

As more functionality is needed (for instance, rendering of notes), more fields can be added to the network table and commented on here. After the initial update to this system, we can swap to using feature branches for each additional function added to the app, and make individual issues for the creation of each feature, while leaving this issue open to refer to.

**Comment by aidnem** [comment]
@jkleiber Initial migration is complete, I'll leave this issue open and use it as documentation for the network table, and then make a pull request for the new code into the main branch soon.
Any future updates to the network table specification can be added here and then have new issues created and new feature branches for them.
In my opinion, having a standard specified here would be better than having it defined over multiple issues spread across the repository.

**Comment by jkleiber** [comment]
Normally what I would recommend to define a standard would be to include it as a doc checked into the repo's version control itself rather than relying on the issue system. For now that could be a simple markdown file in a doc/ folder with a table of fields and what they represent

**Comment by aidnem** [comment]
Okay, I'll add that
